version: '3'
services:

  php:
    build: phpImage
    depends_on:
      - database
    ports:
    - 80:80
    volumes:
    - ./server:/server
    networks:
      - symfonyDb
      - symfonyExternal

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: phjs_database
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - symfonyDb
      - pmaDb


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - pmaDb
      - pmaExternal

networks:
  symfonyExternal:
    internal: false
  pmaExternal:
    internal: false
  symfonyDb:
    internal: true
  pmaDb:
    internal: true